---
version: 1.0.2
hassio_api: true
hassio_role: default
ingress: true
#ingress_port: 8099
panel_title: Hass Remote
panel_icon: mdi:remote-desktop
slug: hass_remote
name: Hass_Remote
description: Remote Access Your Hass from Anywhere
url: https://sumju.net
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  key: "xxxxxxxxxxxxxxxx"
schema:
  key: str
image: "ghcr.io/5high/{arch}-addon-hass-remote"
