---
version: 1.0.0
hassio_api: true
hassio_role: default
ingress: true
#ingress_port: 8099
panel_title: 远程访问插件大陆版/Hass Remote CN
panel_icon: mdi:remote-desktop
slug: hass_remote_cn
name: Hass_Remote_CN
description: Remote Access Your Hass from Anywhere (中国大陆版本)
url: https://sumju.net
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: homeassistant/{arch}-addon-nginx_proxy
init: false
options:
  key: "xxxxxxxxxxxxxxxx"
schema:
  key: str
