name: "Publish Aliyun Backup"

on:
  push:
    branches:
      - main
    paths:
      - 'addons/aliyun_backup/**'
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 5high
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addons/aliyun_backup \
            --docker-hub ghcr.io/5high
