name: "Publish"

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64, amd64, armhf, armv7, i386]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish build - Home Assistant builder
        uses: home-assistant/builder@master
        with:
          args: |
            --${{matrix.target}} \
            --target addons/aliyun_backup/
