name: "Publish Hass Remote"

on:
  push:
    branches:
      - main
    paths:
      - 'addons/hass_remote/**'
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 5high
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addons/hass_remote \
            --docker-hub ghcr.io/5high
