name: "Publish Aliyun Backup"

on:
  push:
    branches:
      - main
    paths:
      - 'addons/aliyun_backup/**'
  workflow_dispatch:

jobs:
  build:
    name: Docker Image build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 5high
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addons/aliyun_backup \
            --docker-hub 5high
